name: enough_mail_html
description: Generate HTML from an email mime message. Eases handling of `MimeMessage` in the `enough_mail` package.
version: 0.1.1
homepage: https://github.com/Enough-Software/enough_mail_html

environment:
  sdk: '>=2.9.3 <3.0.0'

dependencies:
  html: ^0.14.0+4
  enough_mail: ^0.0.34 
    # path: ../enough_mail/

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
