name: enough_mail_html
description: Generate HTML from an email mime message and creates plain text from HTML. Eases handling of `MimeMessage` in the `enough_mail` package.
version: 1.3.0
homepage: https://github.com/Enough-Software/enough_mail_html

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  html: ^0.15.0
  enough_mail: #^1.3.3
    # git:
    #   url: https://github.com/Enough-Software/enough_mail.git
    path: ../enough_mail/
  image: ^3.0.2

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.7
