name: enough_mail_html
description: Generate HTML from an email mime message. Eases handling of `MimeMessage` in the `enough_mail` package.
version: 0.2.1
homepage: https://github.com/Enough-Software/enough_mail_html

environment:
  sdk: '>=2.9.3 <3.0.0'

dependencies:
  html: ^0.14.0+4
  enough_mail: #^0.1.0
    git:
      url: https://github.com/Enough-Software/enough_mail.git
      ref: main
    # path: ../enough_mail/
  image: ^2.1.19

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
